<?php

/**
 * @file
 * Module file for the Better field descriptions module.
 *
 * The module hooks into forms and adds a better description to fields.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Xss;
use Drupal\Core\Render\Element;

/**
 * Implements hook_help().
 */
function better_field_descriptions_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.better_field_descriptions') {
    return t('Allows users with certain roles to add themeable descriptions to fields in forms. The module consists of two parts. One is configuring which fields in which content types that should be configured to have a better description. The other part is editing the descriptions themselves.');
  }
}

/**
 * Implements hook_theme().
 */
function better_field_descriptions_theme($existing, $type, $theme, $path) {

  $bfd = \Drupal::config('better_field_descriptions.settings')->get('better_field_descriptions');

  // Find the theme template or use default if not configured.
  if (isset($bfd['template']) == FALSE || empty($bfd['template'])) {
    $template_file = 'better-field-descriptions-fieldset';
  }
  else {
    $template_file = $bfd['template'];
  }

  // Find the theme template URI .
  if ($template_file == 'better-field-descriptions-fieldset') {
    $template_uri = drupal_get_path('module', 'better_field_descriptions') . '/templates';
  }
  else {
    $template_uri = $bfd['template_uri'];
    $template_uri = str_replace('/' . $template_file . '.html.twig', '', $template_uri);
  }

  return [
    'better_field_descriptions' => [
      'variables' => ['label' => NULL, 'description' => NULL],
      'template' => $template_file,
      'path' => $template_uri,
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Future improvements: add a theming function for the #suffix content. Users
 * could then add their own template and select template from the settings page.
 */
function better_field_descriptions_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $bundle = $form_state->getFormObject()->getEntity()->getType();

  // Get better descriptions.
  $bfd = \Drupal::config('better_field_descriptions.settings')->get('better_field_descriptions');

  // Only add descriptions if the bundle field is configured with one.
  if (isset($bfd[$bundle])) {
    $form['#attached']['library'][] = 'core/drupal.form';
    $form['#attached']['library'][] = 'core/drupal.collapse';
    $form['#after_build'][] = 'better_field_descriptions_after_build';
  }
}

/**
 * Adds better field descriptions to node form.
 *
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state.
 *
 * @return array
 *   The form array with better help text.
 */
function better_field_descriptions_after_build(array $form, FormStateInterface $form_state) {
  $bundle = $form_state->getFormObject()->getEntity()->getType();

  // Get better descriptions.
  $bfd = \Drupal::config('better_field_descriptions.settings')->get('better_field_descriptions');

  // Only add descriptions if the bundle field is configured with one.
  if (isset($bfd[$bundle])) {

    // Default label.
    $default_label = Xss::filter($bfd['default_label']);

    // Available positions.
    $positions = [0 => '#prefix', 1 => '#suffix', 2 => 'between'];

    // Adding description to field if configured.
    foreach ($bfd[$bundle] as $field => $data) {
      if (isset($form[$field]) && !empty($data['description'])) {

        // Set position if configured or set default to #suffix.
        $position = isset($data['position']) ? $positions[$data['position']] : '#suffix';

        // The description as configured.
        $description = $data['description'];

        // Reference the widget for convenience.
        $widget =& $form[$field]['widget'];

        // In many cases we want the first child of the widget instead.
        $use_child = FALSE;
        if (!isset($widget['#title'])) {
          $use_child = TRUE;
        }

        if ($use_child) {
          $child_keys = Element::children($widget, TRUE);
          if (!empty($child_keys)) {
            $widget =& $form[$field]['widget'][current($child_keys)];
          }
        }

        switch ($position) {

          case '#suffix':
          case '#prefix':

            $label = empty($data['label'])
              ? $default_label
              : $data['label'];
            break;

          case 'between':

            $label = (empty($data['label']) && !empty($widget['#title']))
              ? $widget['#title']
              : $data['label'];

            $widget['#title_display'] = 'invisible';
            // In some widgets, the title is duplicated and must also be hidden.
            better_field_descriptions_hide_duplicate_titles($widget, $widget['#title']);
            $position = '#prefix';
            break;
        }

        $output = [
          '#theme' => 'better_field_descriptions',
          '#label' => Xss::filter($label),
          '#description' => Xss::filter($description),
        ];
        $output = \Drupal::service('renderer')->render($output);

        // Add description to element, appending to other markup if present.
        if (!isset($widget[$position])) {
          $widget[$position] = '';
        }
        $widget[$position] .= $output;
      }
    }
  }
  return $form;
}

/**
 * Sets display of duplicate titles in children to 'invisible'.
 *
 * @param array &$element
 *   The widget render array.
 * @param string $title
 *   The title to be hidden if present.
 */
function better_field_descriptions_hide_duplicate_titles(array &$element, $title) {
  foreach (Element::children($element) as $key) {
    if (isset($element[$key]['#title']) && $title == $element[$key]['#title']) {
      $element[$key]['#title_display'] = 'invisible';
      // Recurse into children of this element (some widgets triplicate).
      better_field_descriptions_hide_duplicate_titles($element[$key], $title);
    }
  }
}
